name: CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install --verbose
        env:
          VITE_STAGE: ${{ secrets.VITE_STAGE }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_ENABLE_API_DELAY: ${{ secrets.VITE_ENABLE_API_DELAY }}

      - name: Build project
        run: npm run build
        env:
          VITE_STAGE: ${{ secrets.VITE_STAGE }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_ENABLE_API_DELAY: ${{ secrets.VITE_ENABLE_API_DELAY }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::629500205300:role/vb-hub-dashboard-react-build-s3
          aws-region: us-east-1

      - name: Deploy to S3 Bucket
        run: |
          aws s3 sync dist/ s3://www.hubdash.space --delete